name: Q Code Transformation

on:
  push:
    branches:
      - 'Q-TRANSFORM-issue-*'

jobs:
  q-code-transformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./DotNetMinimalAPIDemo/MinimalAPIDemo.sln
      - name: Build
        run: dotnet build ./DotNetMinimalAPIDemo/MinimalAPIDemo.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ./DotNetMinimalAPIDemo/MinimalAPIDemo.sln --configuration Release --no-build --verbosity normal
      - name: Publish
        run: dotnet publish ./DotNetMinimalAPIDemo/MinimalAPIDemo.sln --configuration Release --no-build --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: q-code-transformation-dependencies
          path: dependencies